### ISSUE TITLE
How to make the rigidbodies exact position by Moving in Unity?

### ISSUE THREAD

**Issue by carvinchen** [ozzyonfire/UnityOptitrack#5]
Good Morning, Matt and others

Thank you for your program, it is very helpful for my project.

I am also using your program to get the positions of optitrack-markers which i am wearing on my finger. I want to touch 3d objects with my finger like i touch a object in real word. It works fun and your script makes it easier.

But if i watch the rigidbodies following my fingers in unity by moving in trackingarea (3d senario), their positions were not so accurate like i wish.

For example i have adjusted the positions of the rigidbodies for finger in your script and they are now exact at the same position like my real fingertip, and from there to the screen is the distance 2 meters. And if i go to the screen nearly and i see the rigidbodies were behinde my hand.

What i am doing wrong? i just have adjusted z - axis to -z- (a number for example. 2.0f) and it means 2 meters far away from the screen.

Any idea? sorry for my bad english.

Thank your and have a nice day.

Carvin

**Comment by ozzyonfire** [comment]
The orientation of your hand during the creation of the rigid body in motive will change how it looks in unity. Play around with the numbers in the code. You may have to make something negative in order to flip your rigid body.

Also, it sounds like you want the markers to show up in Unity and not just the rigid body. This is possible, but not implemented yet, depending on your coding experience you may be able to figure it out.

The 2 in the z axis doesn’t necessarily mean 2 meters so change that number to whatever works.

Matt

On May 12, 2015, at 5:24 AM, carvinchen <notifications@github.com<mailto:notifications@github.com>> wrote:

Good Morning, Matt and others

Thank you for your program, it is very helpful for my project.

I am also using your program to get the positions of optitrack-markers which i am wearing on my finger. I want to touch 3d objects with my finger like i touch a object in real word. It works fun and your script makes it easier.

But if i watch the rigidbodies following my fingers in unity by moving in trackingarea (3d senario), their positions were not so accurate like i wish.

For example i have adjusted the positions of the rigidbodies for finger in your script and they are now exact at the same position like my real fingertip, and from there to the screen is the distance 2 meters. And if i go to the screen nearly and i see the rigidbodies were behinde my hand.

What i am doing wrong? i just have adjusted z - axis to -z- (a number for example. 2.0f) and it means 2 meters far away from the screen.

Any idea? sorry for my bad english.

Thank your and have a nice day.

Carvin

**Comment by carvinchen** [comment]
Hi, Matt 

Thank you for your answer. 

I think, the content of my queston is maybe not understandable for you, sorry. 

I have already created rigidbodies for the markers in Motive which i am showing as gameobject in Unity und given them the right numbers. It works fun.

The orientation of my 3d finger-objects in Unity i have already adjusted, because they had different / wrong rotations, but now they looks good. 

But if i am wearing the markers and stay 2 meter far away from the screen that shows the 3d senario / 3d objects, my 3d finger objects should also show on the screen at the same position like my real finger, i think? 

But they are not, they are (for example 0.2 or 0.3 meter in front of me / my real finger), so after i adjusted the position in script ( actually all 3 axis must be adjusted, for distance to screen: z-axis ), i get the same position like my real fingertip, and they are in front of my finger too, good.

But if i go to screen nearly (for example 0.6 meter to screen or wall ), i see the 3d finger objects are behinde my fingertips, they should in front of them. 

How could i do it better? This is my Question :) 

Thank you (Danke dir). 

Carvin

**Comment by ozzyonfire** [comment]
Hmm. you are still going to have to play with the numbers and the scale. Sorry I can’t be of more help. I’m not involved with any motive stuff anymore so I am just giving suggestions from memory.

On May 12, 2015, at 9:19 AM, carvinchen <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, Matt

Thank you for your answer.

I think, the content of my queston is maybe not understandable for you, sorry.

I have already created rigidbodies for the markers in Motive which i am showing as gameobject in Unity und given them the right numbers. It works fun.

The orientation of my 3d finger-objects in Unity i have already adjusted, because they had different / wrong rotations, but now they looks good.

But if i am wearing the markers and stay 2 meter far away from the screen that shows the 3d senario / 3d objects, my 3d finger objects should also show on the screen at the same position like my real finger, i think?

But they are not, they are (for example 0.2 or 0.3 meter in front of me / my real finger), so after i adjusted the position in script ( actually all 3 axis must be adjusted, for distance to screen: z-axis ), i get the same position like my real fingertip, and they are in front of my finger too, good.

But if i go to screen nearly (for example 0.6 meter to screen or wall ), i see the 3d finger objects are behinde my fingertips, they should in front of them.

How could i do it better? This is my Question :)

Thank you (Danke dir).

Carvin

**Comment by DanWuh** [comment]
Hey Carvin,  ive been working on similar workflows and ive noticed that I frequently have to either reapply current orientation in Motive during testing phases or in some cases remove and regenerate the rigid body.  I think a lot of the time, narrow/shallow rigid bodies sometimes, over testing iterations, loose their valid orientations. I ran into it a lot when using rigid bodies generated from markers placed linearly on the oculus.  Just something I had ran into, a bit late to this party of course so perhaps you already fixed this.
